# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictByAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Districts', models.CharField(max_length=150, verbose_name='District')),
                ('Total_Population', models.IntegerField()),
                ('Male', models.IntegerField()),
                ('Female', models.IntegerField()),
                ('Ages_0_14_total', models.IntegerField(verbose_name='Ages 0-14 Total')),
                ('Ages_0_14_male', models.IntegerField(verbose_name='Ages 0-14 Male')),
                ('Ages_0_14_female', models.IntegerField(verbose_name='Ages 0-14 Female')),
                ('Ages_15_64_total', models.IntegerField(verbose_name='Ages 15-64 Total')),
                ('Ages_15_64_male', models.IntegerField(verbose_name='Ages 15-64 Male')),
                ('Ages_15_64_female', models.IntegerField(verbose_name='Ages 15-64 Female')),
                ('Ages_65_abv_total', models.IntegerField(verbose_name='Ages 65+ Total')),
                ('Ages_65_abv_male', models.IntegerField(verbose_name='Ages 65+ Male')),
                ('Ages_65_abv_female', models.IntegerField(verbose_name='Ages 65+ Female')),
                ('Region', models.CharField(max_length=150)),
            ],
        ),
    ]
