# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180118_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=128)),
                ('Capital', models.CharField(max_length=128)),
                ('Total', models.IntegerField()),
                ('Male', models.IntegerField()),
                ('Female', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionalPopulationByAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=128)),
                ('Capital', models.CharField(max_length=128)),
                ('Total', models.IntegerField()),
                ('Male', models.IntegerField()),
                ('Female', models.IntegerField()),
                ('Ages_0_14', models.IntegerField(verbose_name='Ages 0-14')),
                ('Ages_15_60', models.IntegerField(verbose_name='Ages 15-65')),
                ('Ages_65_abv', models.IntegerField(verbose_name='Ages 65+')),
            ],
        ),
        migrations.RemoveField(
            model_name='districtbyagegroup',
            name='Capital',
        ),
    ]
