# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_regionalpopulationbyreligiousaffiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPopulationByNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=125)),
                ('Capital', models.CharField(max_length=125)),
                ('Total', models.IntegerField()),
                ('by_birth', models.FloatField(verbose_name='% By Birth')),
                ('by_naturalisation', models.FloatField(verbose_name='% By Naturalisation')),
                ('non_Ghanaian', models.FloatField(verbose_name='% Non Ghanaian')),
                ('by_birth_population', models.IntegerField(verbose_name='By Birth')),
                ('by_Naturalisation_population', models.IntegerField(verbose_name='By Naturalisation')),
                ('Non_Ghanaian_population', models.IntegerField(verbose_name='Non Ghanaian')),
            ],
            options={
                'verbose_name_plural': 'Regional Population By Nationality',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalpopulationbyreligiousaffiliation',
            options={'verbose_name_plural': 'Regional Population By Religious Affiliation'},
        ),
    ]
