# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 07:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180118_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=120, verbose_name='File Name')),
                ('Upload_Date', models.DateField()),
                ('File', models.FileField(upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
            ],
            options={
                'verbose_name_plural': 'CSV Files',
            },
        ),
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=120, verbose_name='File Name')),
                ('Upload_Date', models.DateField()),
                ('File', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Image Files',
            },
        ),
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=120, verbose_name='File Name')),
                ('Upload_Date', models.DateField()),
                ('File', models.FileField(upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'verbose_name_plural': 'Pdf Files',
            },
        ),
    ]
