# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_csvfiles_imagefiles_pdffiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('multipoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('multiline', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Shape Files',
            },
        ),
    ]
