# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='geometryCollection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='multiline',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='multipoint',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
