# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180319_0858'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feature',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
