# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180319_0907'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feature',
            managers=[
            ],
        ),
    ]
