# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180319_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalpopulationbyreligiousaffiliation',
            name='Region',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
