# Generated by Django 2.0.5 on 2018-05-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180401_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='line',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='multiline',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='multipoint',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='multipolygon',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='point',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='polygon',
        ),
    ]
